spring:
  application:
    name: "api-gateway"
  cloud:
    gateway:
      routes:
        - id: customers-service
          uri: http://localhost:8081
#          uri: lb://customers-service
          predicates:
            - Path=/customers/**
          filters:
            - StripPrefix=1
        - id: orders-service
          uri: http://localhost:8083
#          uri: lb://orders-service
          predicates:
            - Path=/orders/**
          filters:
            - StripPrefix=1
        - id: products-service
          uri: http://localhost:8082
#          uri: lb://products-service
          predicates:
            - Path=/products/**
          filters:
            - StripPrefix=1

server:
  port: 8889

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
